TRAILERS_FOLDER: "/Volumes/Seagate/natasha-diploma/trailers_mp4/"
VIDEO_INFO_FOLDER: "/Volumes/Seagate/natasha-diploma/videoinfo/"
AUDIO_FOLDER: "/Volumes/Seagate/natasha-diploma/audio_wav/"
AUDIO_INFO_FOLDER: "/Volumes/Seagate/natasha-diploma/audioinfo/"